version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "gradle"
    target-branch: "develop"
    commit-message:
      prefix: "chore(deps): "
      include: "scope"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    allow:
      - dependency-type: "direct"
    assignees:
      - "hywenklis"
    reviewers:
      - "hywenklis"
      - "genesluna"
      - "FSLucas22"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"
    target-branch: "develop"
    commit-message:
      prefix: "chore(actions): "
      include: "scope"
    allow:
      - dependency-name: "actions/*"
    assignees:
      - "hywenklis"
    reviewers:
      - "hywenklis"
      - "genesluna"
      - "FSLucas22"