version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 5
    groups:
      gradle-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
        versioning-strategy: "increase"
      gradle-major:
        patterns:
          - "*"
        update-types:
          - "major"
        versioning-strategy: "increase"
    labels:
      - "dependencies"
      - "gradle"
      - "security"
    target-branch: "develop"
    commit-message:
      prefix: "chore(deps): "
      include: "scope"
    allow:
      - dependency-type: "direct"
    assignees:
      - "hywenklis"
    reviewers:
      - "hywenklis"
      - "genesluna"
      - "FSLucas22"
    pull-request-branch-name:
      separator: "-"
    rebase-strategy: "auto"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "09:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 3
    groups:
      github-actions-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      github-actions-major:
        patterns:
          - "*"
        update-types:
          - "major"
    labels:
      - "dependencies"
      - "github-actions"
      - "security"
    target-branch: "develop"
    commit-message:
      prefix: "chore(actions): "
      include: "scope"
    assignees:
      - "hywenklis"
    reviewers:
      - "hywenklis"
      - "genesluna"
      - "FSLucas22"
    pull-request-branch-name:
      separator: "-"
    rebase-strategy: "auto"
