[github_app]
pr_commands = [
    "/improve",
    "/update_changelog",
    "/git_log"
]

[git_log]
executable = "git"
args = [
    "log",
    "-n",
    "5",
    "--pretty=fuller"
]

[best_practices]
enable_global_best_practices = true #

[auto_best_practices]
enable_auto_best_practices = true #
utilize_auto_best_practices = true

[pr_update_changelog]
push_changelog_changes = false # set true to push a commit; false = comment only
add_pr_link = true # include PR link
extra_instructions = """\
Follow these rules to create the changelog entry:

1.  **Title:** Start with a clear, descriptive title that summarizes the pull request.
2.  **PR Link:** Directly below the title, add a link to the pull request, formatted like this: `*PR: [#123](https://github.com/owner/repo/pull/123)*`.
3.  **Sections:** Group all changes into the standard categories: `### Added`, `### Changed`, and `### Fixed`.
4.  **Change Details:** List each change as a bullet point.
5.  **PR Author:** At the very end of the entry, credit the main author of the pull request, like this: `**PR Author:** @username`.
"""
