[github_app]
pr_commands = [
    "/improve"
]

[best_practices]
enable_global_best_practices = true #

[auto_best_practices]
enable_auto_best_practices = true #
utilize_auto_best_practices = true

[pr_update_changelog]
push_changelog_changes = false # set true to push a commit; false = comment only
add_pr_link = true # include PR link
