[github_app]
pr_commands = [
    "/improve",
    "/update_changelog"
]

[best_practices]
enable_global_best_practices = true #

[auto_best_practices]
enable_auto_best_practices = true #
utilize_auto_best_practices = true

[pr_update_changelog]
push_changelog_changes = false # set true to push a commit; false = comment only
add_pr_link = true # include PR link
extra_instructions = """\

Include a clear changelog entry title.
For each included change, add a commit link and list the commit author(s).
At the end of the entry, add the PR author.
"""
