spring:
  profiles:
    active: local

resilience4j:
  retry:
    instances:
      tokenBlocklist:
        max-attempts: 3
        wait-duration: 200ms
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        retry-exceptions:
          - org.springframework.dao.DataAccessException
          - io.lettuce.core.RedisException
