name: CI Tests

on:
  push:
    branches:
      - master
      - main
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - master
      - main
      - develop
      - 'release/*'
      - 'hotfix/*'

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      issues: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Use Gradle Cache
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build and test with Gradle wrapper
        run: |
          chmod +x gradlew
          ./gradlew clean build test jacocoTestReport

