name: Code Review com IA

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - develop
      - 'release/*'
      - 'hotfix/*'

permissions:
  contents: read
  pull-requests: write
  security-events: write

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      issues: read
      checks: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Obter diff da PR
        id: diff
        run: |
          git fetch origin --unshallow || true
          DIFF=$(git diff ${{ github.event.pull_request.base.sha }}...${{ github.event.pull_request.head.sha }})
          echo "$DIFF" > diff.txt
          if [ -z "$DIFF" ] || [ ${#DIFF} -lt 50 ]; then
            echo "SKIP_REVIEW=true" >> $GITHUB_ENV
            echo "⚠️ Diff vazio ou muito pequeno, pulando revisão."
          else
            echo "SKIP_REVIEW=false" >> $GITHUB_ENV
          fi

      - name: Gerar resumo com IA
        id: generate_summary
        if: ${{ env.SKIP_REVIEW == 'false' }}
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        run: |
          ESCAPED_DIFF=$(jq -Rs . < diff.txt)

          cat > payload.json <<EOF
          {
            "model": "deepseek/deepseek-chat-v3-0324:free",
            "messages": [
              {
                "role": "system",
                "content": "Você é um engenheiro de software experiente e revisor de código. Analise o diff de código fornecido e gere um resumo em formato markdown para um comentário de Pull Request. O resumo deve estar em PORTUGUÊS BRASILEIRO, ser claro, técnico e estruturado com os seguintes tópicos:\n\n1. **Visão Geral**: breve descrição do que a PR faz;\n2. **Propósito**: o motivo das alterações e o problema que resolve ou funcionalidade adicionada;\n3. **Alterações**: lista dos arquivos modificados com explicações detalhadas de cada mudança, incluindo trechos relevantes em blocos de código;\n4. **Impacto**: como essas alterações afetam o sistema (funcionalidade, desempenho, manutenção);\n5. **Testes**: como foi testado e se houve adição de novos testes;\n6. **Sugestões de Melhoria**: recomende melhorias técnicas com explicações claras, baseadas em boas práticas (ex: legibilidade, performance, desacoplamento, padrão de projeto, SOLID, etc);\n7. **Notas**: qualquer observação relevante, como dependências ou próximos passos.\n\nA resposta deve estar em Markdown puro, com cabeçalhos, listas e blocos de código bem formatados."
              },
              {
                "role": "user",
                "content": $ESCAPED_DIFF
              }
            ]
          }
          EOF
      
          RESPONSE=$(curl -s https://openrouter.ai/api/v1/chat/completions \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer $OPENROUTER_API_KEY" \
          --data-binary @payload.json)
        
          SUMMARY=$(echo "$RESPONSE" | jq -r '.choices[0].message.content // ""')
        
          if [ -z "$SUMMARY" ]; then
          echo "⚠️ Resumo não gerado pela IA, usando fallback."
          SUMMARY="# Resumo da PR\n\nNenhuma descrição detalhada gerada. Alterações detectadas no diff, mas sem resumo específico."
          fi
          
          echo "$SUMMARY" > summary.md
          echo "has_summary=true" >> $GITHUB_OUTPUT

      - name: Atualizar descrição da PR com o resumo
        if: ${{ env.SKIP_REVIEW == 'false' && steps.generate_summary.outputs.has_summary == 'true' }}
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const summary = fs.readFileSync('summary.md', 'utf8');
            
            if (!summary.trim()) {
              console.log("⚠️ Resumo vazio, não atualizando descrição.");
              return;
            }
            
            const { owner, repo } = context.repo;
            const pull_number = context.payload.pull_request.number;
            
            const { data: pr } = await github.rest.pulls.get({
              owner,
              repo,
              pull_number
            });
            
            const novaDescricao = `### 🤖 Resumo automático da IA\n\n${summary}\n\n---\n📝 _Este resumo foi gerado automaticamente por IA com base nas alterações da PR. Sugestões e melhorias estão incluídas._\n\n---\n${pr.body || ''}`.trim();
            
            await github.rest.pulls.update({
              owner,
              repo,
              pull_number,
              body: novaDescricao
            });
            
            console.log("✅ Descrição da PR atualizada com sucesso.");
